[versions]
kotlin = "1.8.0"
ksp = "1.8.0-1.0.9"
androidGradlePlugin = "8.2.1"

desugar = "2.0.3"
coroutines = "1.6.4"

lifecycle = "2.6.2"

navigation = "2.3.5"

fragmentKtx = "1.6.1"
coreKtx = "1.10.1"
appCompat = "1.6.1"
constraintLayout = "2.1.4"
room = "2.5.2"
securityCryptoKtx = "1.1.0-alpha06"
workRuntime = "2.4.0"
test = "1.5.0"
androidxjUnit = "4.13.2"
espresso = "3.5.1"
fragment-testing = "1.6.1"
core-testing = "2.2.0"

okhttp = "4.11.0"
retrofit = "2.9.0"
moshi = "1.15.0"

material = "1.9.0"
glide = "4.11.0"

timber = "5.0.1"
leakCanary = "2.10"

jUnit = "4.13.2"
harmcrest = "2.2"
robolectric = "4.3.1"

mapbox = "10.6.2"
mapscaleview = "1.6.0"

[libraries]

navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
navigation-dynamic-features-fragment = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "navigation" }
navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "navigation" }

desugar-jdk = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
desugar-jdk-nio = { module = "com.android.tools:desugar_jdk_libs_nio", version.ref = "desugar" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }

kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

androidx-fragmentKtx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
androidx-constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
androidx-roomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-workRuntime = {module = "androidx.work:work-runtime-ktx", version.ref = "workRuntime"}
androidx-testCore = { module = "androidx.test:core", version.ref = "test" }
androidx-testRules = { module = "androidx.test:rules", version.ref = "test" }
androidx-testJUnit = { module = "androidx.test.ext:junit", version.ref = "androidxjUnit" }
androidx-testEspresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-fragmentTesting = { module = "androidx.fragment:fragment-testing", version.ref = "fragment-testing" }
androidx-coreTesting = { module = "androidx.arch.core:core-testing", version.ref = "core-testing" }
androidx-securityCrypto = { module = "androidx.security:security-crypto-ktx", version.ref = "securityCryptoKtx" }

material = { module = "com.google.android.material:material", version.ref = "material" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide"}

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

mapbox = { module = "com.mapbox.maps:android", version.ref = "mapbox" }
mapscaleview = { module = "com.github.pengrad:mapscaleview", version.ref = "mapscaleview" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
leakCanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }

jUnit = { module = "junit:junit", version.ref = "jUnit" }
harmcrest = { module = "org.harmcrest:harmcrest", version.ref = "harmcrest" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

[bundles]
navigation = ["navigation-fragment", "navigation-ui", "navigation-dynamic-features-fragment"]
desugar = ["desugar-jdk", "desugar-jdk-nio"]
coroutines = ["coroutines-core", "coroutines-android"]
lifecycle = ["lifecycle-viewmodel", "lifecycle-livedata"]
remote = ["retrofit", "moshi", "moshi-kotlin", "converter-moshi", "logging-interceptor"]
local = ["androidx-roomRuntime", "androidx-roomKtx"]
map = ["mapbox","mapscaleview"]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
