#!/usr/bin/env bash

echo "Running git pre-commit hooks..."
for hook in "$(dirname "$0")/pre-commit.d"/*; do
    "$hook"
    RESULT=$?
    if [ $RESULT != 0 ]; then
        echo "pre-commit.d/$hook returned non-zero: $RESULT, abort commit"
        exit $RESULT
    fi
done

exit